parameters:
    acl_tables:
        class: %security.acl.dbal.class_table_name%
        entry: %security.acl.dbal.entry_table_name%
        oid: %security.acl.dbal.oid_table_name%
        oid_ancestor: %security.acl.dbal.oid_ancestors_table_name%
        sid: %security.acl.dbal.sid_table_name%
    nuxia.manager.acl_identifier_class: Nuxia\AclBundle\Manager\AclIdentifier
    nuxia.manager.acl_manager_class: Nuxia\AclBundle\Manager\AclManager
    nuxia.manager.acl_checker_class: Nuxia\AclBundle\Manager\AclChecker
    nuxia.manager.acl_filter_class: Nuxia\AclBundle\Manager\AclFilter
    nuxia.twig.acl_extension_class: Nuxia\AclBundle\Twig\AclExtension

services:
    nuxia_acl.acl_identifier:
        class: %nuxia.manager.acl_identifier_class%
        arguments:
            -
            - "@security.acl.provider"
            - "@security.acl.dbal.connection"
            - %acl_tables%

    nuxia_acl.acl_manager:
        class: %nuxia.manager.acl_manager_class%
        arguments:
            - "@nuxia_acl.acl_identifier"
            - "@security.acl.provider"
        calls:
            - [ setPermissionMap, [ "@nuxia_acl.permission_map" ] ]

    nuxia_acl.acl_checker:
        class: %nuxia.manager.acl_checker_class%
        arguments:
            - "@nuxia_acl.acl_identifier"
            -
            - "@security.access.decision_manager"

    nuxia_acl.acl_filter:
        class: %nuxia.manager.acl_filter_class%
        arguments:
            - "@nuxia_acl.acl_identifier"
            - "@security.role_hierarchy"
            -
            - %acl_tables%
        calls:
            - [ setPermissionMap, [ "@nuxia_acl.permission_map" ] ]

    nuxia_acl.twig.acl_extension:
        class: %nuxia.twig.acl_extension_class%
        arguments:
            - "@nuxia_acl.acl_checker"
        tags:
            - { name: twig.extension }
